NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

[DOCUMENTATION]
ORG_NAME=""
ORG_URL=""
ORG_DBA=""
ORG_LOGO=""
ORG_DESCRIPTION=""

[[CURRENCIES]]
code=""
issuer=""
name=""
desc=""
image=""
is_asset_anchored=false
display_decimals=7
status="live"
